# Generated by Django 2.1.3 on 2018-11-23 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0, max_length=6)),
                ('start', models.TimeField(auto_now_add=True)),
                ('end', models.TimeField(auto_now_add=True)),
                ('date', models.TimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='static/pictures/'),
        ),
    ]
