# Generated by Django 2.1.3 on 2018-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20181123_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
