# Generated by Django 2.1.3 on 2018-11-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20181123_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name_plural': 'Teacher Free Times'},
        ),
    ]
